// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: internal/p2p/proto/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// APIRequest is the generic request wrapper for all P2P API protocols.
// Used by: sessions, tasks, approvals, system, secrets, files protocols.
type APIRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request ID for correlation with response.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Method name to invoke (e.g., "list", "get", "create", "delete").
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// JSON-encoded parameters for the method.
	Params        []byte `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIRequest) Reset() {
	*x = APIRequest{}
	mi := &file_internal_p2p_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest) ProtoMessage() {}

func (x *APIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest.ProtoReflect.Descriptor instead.
func (*APIRequest) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *APIRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *APIRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

// APIResponse is the generic response wrapper for all P2P API protocols.
type APIResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlates to the request ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// True if the request was successful.
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// JSON-encoded response data (when success=true).
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Error message (when success=false).
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIResponse) Reset() {
	*x = APIResponse{}
	mi := &file_internal_p2p_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse) ProtoMessage() {}

func (x *APIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse.ProtoReflect.Descriptor instead.
func (*APIResponse) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *APIResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *APIResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *APIResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StreamEvent is used for streaming responses (e.g., logs, real-time updates).
type StreamEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique event ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Event type (e.g., "log", "task_update", "approval_added").
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// JSON-encoded event data.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// True if this is the final event in the stream.
	Done          bool `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_internal_p2p_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *StreamEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StreamEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamEvent) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_internal_p2p_proto_api_proto protoreflect.FileDescriptor

const file_internal_p2p_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/p2p/proto/api.proto\x12\n" +
	"kaggen.p2p\"L\n" +
	"\n" +
	"APIRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06params\x18\x03 \x01(\fR\x06params\"a\n" +
	"\vAPIResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"Y\n" +
	"\vStreamEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04doneB3Z1github.com/yourusername/kaggen/internal/p2p/protob\x06proto3"

var (
	file_internal_p2p_proto_api_proto_rawDescOnce sync.Once
	file_internal_p2p_proto_api_proto_rawDescData []byte
)

func file_internal_p2p_proto_api_proto_rawDescGZIP() []byte {
	file_internal_p2p_proto_api_proto_rawDescOnce.Do(func() {
		file_internal_p2p_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_p2p_proto_api_proto_rawDesc), len(file_internal_p2p_proto_api_proto_rawDesc)))
	})
	return file_internal_p2p_proto_api_proto_rawDescData
}

var file_internal_p2p_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_p2p_proto_api_proto_goTypes = []any{
	(*APIRequest)(nil),  // 0: kaggen.p2p.APIRequest
	(*APIResponse)(nil), // 1: kaggen.p2p.APIResponse
	(*StreamEvent)(nil), // 2: kaggen.p2p.StreamEvent
}
var file_internal_p2p_proto_api_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_p2p_proto_api_proto_init() }
func file_internal_p2p_proto_api_proto_init() {
	if File_internal_p2p_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_p2p_proto_api_proto_rawDesc), len(file_internal_p2p_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_p2p_proto_api_proto_goTypes,
		DependencyIndexes: file_internal_p2p_proto_api_proto_depIdxs,
		MessageInfos:      file_internal_p2p_proto_api_proto_msgTypes,
	}.Build()
	File_internal_p2p_proto_api_proto = out.File
	file_internal_p2p_proto_api_proto_goTypes = nil
	file_internal_p2p_proto_api_proto_depIdxs = nil
}
