// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: internal/p2p/proto/auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthHandshake is sent as the first message on an authenticated P2P stream.
// The client must send this before any other protocol messages.
type AuthHandshake struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authentication token (same format as WebSocket tokens).
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Optional metadata for protocol-specific context.
	Metadata      map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthHandshake) Reset() {
	*x = AuthHandshake{}
	mi := &file_internal_p2p_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthHandshake) ProtoMessage() {}

func (x *AuthHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthHandshake.ProtoReflect.Descriptor instead.
func (*AuthHandshake) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthHandshake) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthHandshake) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// AuthResponse is sent by the server after validating the handshake.
type AuthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if authentication succeeded.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if authentication failed.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Assigned session ID for the authenticated connection.
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// User ID derived from the authenticated token.
	UserId        string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_internal_p2p_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AuthResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_internal_p2p_proto_auth_proto protoreflect.FileDescriptor

const file_internal_p2p_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/p2p/proto/auth.proto\x12\n" +
	"kaggen.p2p\"\xa7\x01\n" +
	"\rAuthHandshake\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12C\n" +
	"\bmetadata\x18\x02 \x03(\v2'.kaggen.p2p.AuthHandshake.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"v\n" +
	"\fAuthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userIdB3Z1github.com/yourusername/kaggen/internal/p2p/protob\x06proto3"

var (
	file_internal_p2p_proto_auth_proto_rawDescOnce sync.Once
	file_internal_p2p_proto_auth_proto_rawDescData []byte
)

func file_internal_p2p_proto_auth_proto_rawDescGZIP() []byte {
	file_internal_p2p_proto_auth_proto_rawDescOnce.Do(func() {
		file_internal_p2p_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_p2p_proto_auth_proto_rawDesc), len(file_internal_p2p_proto_auth_proto_rawDesc)))
	})
	return file_internal_p2p_proto_auth_proto_rawDescData
}

var file_internal_p2p_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_p2p_proto_auth_proto_goTypes = []any{
	(*AuthHandshake)(nil), // 0: kaggen.p2p.AuthHandshake
	(*AuthResponse)(nil),  // 1: kaggen.p2p.AuthResponse
	nil,                   // 2: kaggen.p2p.AuthHandshake.MetadataEntry
}
var file_internal_p2p_proto_auth_proto_depIdxs = []int32{
	2, // 0: kaggen.p2p.AuthHandshake.metadata:type_name -> kaggen.p2p.AuthHandshake.MetadataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_p2p_proto_auth_proto_init() }
func file_internal_p2p_proto_auth_proto_init() {
	if File_internal_p2p_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_p2p_proto_auth_proto_rawDesc), len(file_internal_p2p_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_p2p_proto_auth_proto_goTypes,
		DependencyIndexes: file_internal_p2p_proto_auth_proto_depIdxs,
		MessageInfos:      file_internal_p2p_proto_auth_proto_msgTypes,
	}.Build()
	File_internal_p2p_proto_auth_proto = out.File
	file_internal_p2p_proto_auth_proto_goTypes = nil
	file_internal_p2p_proto_auth_proto_depIdxs = nil
}
