// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: internal/p2p/proto/chat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatMessage is sent from client to server to initiate a chat request.
type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique message identifier (generated by client).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Session identifier for conversation continuity.
	// If empty, server assigns based on peer ID.
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// User identifier (optional, defaults to peer ID).
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Text content of the message.
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// Event ID to reply to (for thread forking).
	ReplyToEventId string `protobuf:"bytes,5,opt,name=reply_to_event_id,json=replyToEventId,proto3" json:"reply_to_event_id,omitempty"`
	// Key-value metadata (values are JSON-encoded bytes).
	Metadata map[string][]byte `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// File attachments.
	Attachments   []*Attachment `protobuf:"bytes,7,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_internal_p2p_proto_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetReplyToEventId() string {
	if x != nil {
		return x.ReplyToEventId
	}
	return ""
}

func (x *ChatMessage) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ChatMessage) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

// Attachment represents a file attached to a message.
type Attachment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Original filename.
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	// MIME type (e.g., "image/jpeg").
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Raw file data.
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_internal_p2p_proto_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Attachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ChatResponse is streamed from server to client.
type ChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique response identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the message this responds to.
	MessageId string `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Session identifier.
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Response content (text, error message, JSON for tool calls, etc.).
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// Response type: session, text, done, error, tool_call, tool_result,
	// thread_created, approval_required.
	Type string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	// True if this is the final response for the message.
	Done bool `protobuf:"varint,6,opt,name=done,proto3" json:"done,omitempty"`
	// Additional metadata (JSON-encoded values).
	Metadata      map[string][]byte `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_internal_p2p_proto_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ChatResponse) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_internal_p2p_proto_chat_proto protoreflect.FileDescriptor

const file_internal_p2p_proto_chat_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/p2p/proto/chat.proto\x12\n" +
	"kaggen.p2p\"\xd4\x02\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12)\n" +
	"\x11reply_to_event_id\x18\x05 \x01(\tR\x0ereplyToEventId\x12A\n" +
	"\bmetadata\x18\x06 \x03(\v2%.kaggen.p2p.ChatMessage.MetadataEntryR\bmetadata\x128\n" +
	"\vattachments\x18\a \x03(\v2\x16.kaggen.p2p.AttachmentR\vattachments\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"Y\n" +
	"\n" +
	"Attachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x9f\x02\n" +
	"\fChatResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x12\n" +
	"\x04done\x18\x06 \x01(\bR\x04done\x12B\n" +
	"\bmetadata\x18\a \x03(\v2&.kaggen.p2p.ChatResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B3Z1github.com/yourusername/kaggen/internal/p2p/protob\x06proto3"

var (
	file_internal_p2p_proto_chat_proto_rawDescOnce sync.Once
	file_internal_p2p_proto_chat_proto_rawDescData []byte
)

func file_internal_p2p_proto_chat_proto_rawDescGZIP() []byte {
	file_internal_p2p_proto_chat_proto_rawDescOnce.Do(func() {
		file_internal_p2p_proto_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_p2p_proto_chat_proto_rawDesc), len(file_internal_p2p_proto_chat_proto_rawDesc)))
	})
	return file_internal_p2p_proto_chat_proto_rawDescData
}

var file_internal_p2p_proto_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_p2p_proto_chat_proto_goTypes = []any{
	(*ChatMessage)(nil),  // 0: kaggen.p2p.ChatMessage
	(*Attachment)(nil),   // 1: kaggen.p2p.Attachment
	(*ChatResponse)(nil), // 2: kaggen.p2p.ChatResponse
	nil,                  // 3: kaggen.p2p.ChatMessage.MetadataEntry
	nil,                  // 4: kaggen.p2p.ChatResponse.MetadataEntry
}
var file_internal_p2p_proto_chat_proto_depIdxs = []int32{
	3, // 0: kaggen.p2p.ChatMessage.metadata:type_name -> kaggen.p2p.ChatMessage.MetadataEntry
	1, // 1: kaggen.p2p.ChatMessage.attachments:type_name -> kaggen.p2p.Attachment
	4, // 2: kaggen.p2p.ChatResponse.metadata:type_name -> kaggen.p2p.ChatResponse.MetadataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_p2p_proto_chat_proto_init() }
func file_internal_p2p_proto_chat_proto_init() {
	if File_internal_p2p_proto_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_p2p_proto_chat_proto_rawDesc), len(file_internal_p2p_proto_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_p2p_proto_chat_proto_goTypes,
		DependencyIndexes: file_internal_p2p_proto_chat_proto_depIdxs,
		MessageInfos:      file_internal_p2p_proto_chat_proto_msgTypes,
	}.Build()
	File_internal_p2p_proto_chat_proto = out.File
	file_internal_p2p_proto_chat_proto_goTypes = nil
	file_internal_p2p_proto_chat_proto_depIdxs = nil
}
